---
# tasks file for scheduling-azure

- name: Query Azure for VM data
  azure_rm_virtualmachine:
    resource_group: "{{ resgroup }}"
  delegate_to: localhost
  register: vm_facts
  ignore_errors: true

- debug:
    msg: "{{ vm_facts }}"

- name: Start VM 
  azure_rm_virtualmachine:
    resource_group: "{{ resgroup }}"
    name: "{{ vm_facts }}"
    started: yes
