---
- name: Check for tags
  hosts: localhost
  connection: local
  tasks:

    - name: Get instance data
      ec2_instance_info:
        filters:
          availability-zone: ap-south-1b
      register: instance_data

    - name: Retrieve all tags on an instance
      ec2_tag:
        resource: "{{ item.instance_id }}"
        state: list
        region: ap-south-1
      with_items: "{{ instance_data.instances }}"
      register: ec2_tags

    - debug:
        msg: "{{ item.tags }}"
      with_items: "{{ ec2_tags.results }}"
      register: tags

    - debug:
        msg: "{{ tags.results[*] }}"

    

   
  
