- hosts: local
  connection: local
  vars:
    region: ap-south-1
    
  tasks:
    - name: Gather EC2 facts
      ec2_instance_facts:
        filters:
          instance-state-name: [ "shutting-down", "stopping", "stopped","running" ]
        region: "{{ region }}"
      register: ec2

    - debug: var=ec2

    - name: Terminate EC2 Instance(s)
      debug:
        msg: "instance_ids: {{ item.instance_id }}"
      with_items: "{{ ec2.instances }}"
