--- 
Parameters: 
  BucketName: 
    Description: "Enter a the S3  Name"
    Type: String
  InstanceType: 
    AllowedValues: 
      - t2.micro
      - t2.small
    Default: t2.micro
    Description: "Instance1 EC2 instance type"
    Type: String
  KeyName: 
    Description: "EC2 Key Pair for SSH Access"
    Type: "AWS::EC2::KeyPair::KeyName"
  SecurityGroupIds: 
    ConstraintDescription: "must be list of EC2 security group ids"
    Description: "Security groups that can be used to access the EC2 Resourse"
    Type: "List<AWS::EC2::SecurityGroup::Id>"
Resources: 
  EC2Machine: 
    Properties: 
      ImageId: ami-d783a9b8
      InstanceType: 
        Ref: InstanceType
      KeyName: 
        Ref: KeyName
      SecurityGroupIds: 
        Ref: SecurityGroupIds
    Type: "AWS::EC2::Instance"
  S3Bucket: 
    Properties: 
      BucketName: 
        Ref: BucketName
    Type: "AWS::S3::Bucket"
